import { useState } from 'react';
import { Lightbulb, Shield, Lock, Wrench, UserX, Server, ChevronDown, Check, Clock, Zap, User } from 'lucide-react';
import { mockRecommendations, recommendationSummary } from '../data/mockRecommendations';

const categoryIcons = {
  'Access Control': Lock,
  'Network Security': Shield,
  'Account Security': UserX,
  'System Hardening': Wrench,
  'Containment': Server,
  'Application Security': Zap,
};

const effortColor = { Low: '#00ff88', Medium: '#ffb800', High: '#ff3366' };
const impactColor = { Critical: '#ff3366', High: '#ffb800', Medium: '#a855f7', Low: '#00d4ff' };

function RiskReductionBar({ value }) {
  const color = value >= 80 ? '#00ff88' : value >= 60 ? '#ffb800' : '#a855f7';
  return (
    <div className="flex items-center gap-2">
      <div className="flex-1 h-2 rounded-full" style={{ background: '#1e3a5f' }}>
        <div className="h-full rounded-full transition-all duration-700" style={{ width: `${value}%`, background: `linear-gradient(90deg, ${color}88, ${color})`, boxShadow: `0 0 8px ${color}44` }} />
      </div>
      <span className="text-xs font-bold w-10 text-right" style={{ color }}>{value}%</span>
    </div>
  );
}

export default function Recommendations() {
  const [recs, setRecs] = useState(mockRecommendations);
  const [filter, setFilter] = useState('All');

  const filtered = filter === 'All' ? recs
    : filter === 'Pending' ? recs.filter(r => r.status === 'Pending')
    : recs.filter(r => r.status === 'Applied');

  const markApplied = (id) => {
    setRecs(prev => prev.map(r => r.id === id ? { ...r, status: 'Applied' } : r));
  };

  return (
    <div className="space-y-5 animate-fade-in">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl font-bold text-text-primary">AI Recommendations</h2>
          <p className="text-sm text-text-muted">Automated mitigation strategies generated by AI-SOC</p>
        </div>
        <div className="flex gap-2">
          {['All', 'Pending', 'Applied'].map(f => (
            <button key={f} onClick={() => setFilter(f)}
              className="px-3 py-1.5 rounded text-xs font-medium transition-all"
              style={{
                background: filter === f ? 'rgba(0,212,255,0.15)' : 'rgba(255,255,255,0.03)',
                color: filter === f ? '#00d4ff' : '#64748b',
                border: `1px solid ${filter === f ? '#00d4ff44' : '#1e3a5f'}`,
              }}>
              {f}
            </button>
          ))}
        </div>
      </div>

      {/* Summary */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        <div className="glass-card p-4 text-center" style={{ border: '1px solid rgba(0,212,255,0.2)' }}>
          <p className="text-2xl font-bold" style={{ color: '#00d4ff' }}>{recommendationSummary.total}</p>
          <p className="text-xs text-text-muted mt-0.5">Total Recommendations</p>
        </div>
        <div className="glass-card p-4 text-center" style={{ border: '1px solid rgba(0,255,136,0.2)' }}>
          <p className="text-2xl font-bold" style={{ color: '#00ff88' }}>{recommendationSummary.applied}</p>
          <p className="text-xs text-text-muted mt-0.5">Applied</p>
        </div>
        <div className="glass-card p-4 text-center" style={{ border: '1px solid rgba(255,184,0,0.2)' }}>
          <p className="text-2xl font-bold" style={{ color: '#ffb800' }}>{recommendationSummary.pending}</p>
          <p className="text-xs text-text-muted mt-0.5">Pending</p>
        </div>
        <div className="glass-card p-4 text-center" style={{ border: '1px solid rgba(168,85,247,0.2)' }}>
          <p className="text-2xl font-bold" style={{ color: '#a855f7' }}>{recommendationSummary.avgRiskReduction}%</p>
          <p className="text-xs text-text-muted mt-0.5">Avg Risk Reduction</p>
        </div>
      </div>

      {/* Recommendation cards */}
      <div className="space-y-4">
        {filtered.map((rec, i) => {
          const Icon = categoryIcons[rec.category] || Shield;
          const isApplied = rec.status === 'Applied';
          return (
            <div
              key={rec.id}
              className="glass-card p-5 transition-all duration-200"
              style={{
                border: `1px solid ${isApplied ? 'rgba(0,255,136,0.15)' : rec.priority === 1 ? 'rgba(255,51,102,0.2)' : 'rgba(30,58,95,0.8)'}`,
                opacity: isApplied ? 0.8 : 1,
                animation: `fadeIn 0.2s ease-out ${i * 0.05}s both`,
              }}
            >
              <div className="flex items-start gap-4">
                {/* Priority badge */}
                <div className="flex-shrink-0 text-center">
                  <div className="w-10 h-10 rounded-xl flex items-center justify-center"
                    style={{
                      background: isApplied ? 'rgba(0,255,136,0.1)' : rec.priority === 1 ? 'rgba(255,51,102,0.1)' : 'rgba(255,184,0,0.08)',
                      border: `1px solid ${isApplied ? 'rgba(0,255,136,0.2)' : rec.priority === 1 ? 'rgba(255,51,102,0.2)' : 'rgba(255,184,0,0.15)'}`,
                    }}>
                    {isApplied
                      ? <Check size={18} style={{ color: '#00ff88' }} />
                      : <Icon size={18} style={{ color: rec.priority === 1 ? '#ff3366' : '#ffb800' }} />
                    }
                  </div>
                  <p className="text-xs mt-1 font-bold" style={{ color: '#64748b' }}>#{rec.priority}</p>
                </div>

                {/* Content */}
                <div className="flex-1 min-w-0">
                  <div className="flex items-start justify-between gap-2 flex-wrap">
                    <div>
                      <div className="flex items-center gap-2 mb-1">
                        <span className="text-xs px-2 py-0.5 rounded" style={{ background: 'rgba(168,85,247,0.1)', color: '#a855f7', border: '1px solid rgba(168,85,247,0.2)' }}>
                          {rec.category}
                        </span>
                        <span className="text-xs px-2 py-0.5 rounded"
                          style={{ background: rec.type === 'Automated' ? 'rgba(0,212,255,0.1)' : 'rgba(255,184,0,0.1)', color: rec.type === 'Automated' ? '#00d4ff' : '#ffb800' }}>
                          {rec.type === 'Automated' ? '⚡ Auto' : '👤 Manual'}
                        </span>
                        <span className="text-xs" style={{ color: isApplied ? '#00ff88' : '#ff3366' }}>
                          {isApplied ? '✓ Applied' : '⚠ Pending'}
                        </span>
                      </div>
                      <h4 className="text-sm font-bold text-text-primary">{rec.title}</h4>
                      <p className="text-xs text-text-muted mt-1">{rec.description}</p>
                    </div>
                    <div className="flex-shrink-0 text-right">
                      <div className="flex gap-3">
                        <div>
                          <p className="text-xs text-text-muted">Effort</p>
                          <p className="text-xs font-bold" style={{ color: effortColor[rec.effort] }}>{rec.effort}</p>
                        </div>
                        <div>
                          <p className="text-xs text-text-muted">Impact</p>
                          <p className="text-xs font-bold" style={{ color: impactColor[rec.impact] }}>{rec.impact}</p>
                        </div>
                        <div>
                          <p className="text-xs text-text-muted">ETA</p>
                          <p className="text-xs font-semibold text-text-primary">{rec.timeToImplement}</p>
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Risk reduction */}
                  <div className="mt-3">
                    <div className="flex justify-between text-xs mb-1">
                      <span style={{ color: '#64748b' }}>Risk Reduction</span>
                    </div>
                    <RiskReductionBar value={rec.riskReduction} />
                  </div>

                  {/* Steps */}
                  <details className="mt-3">
                    <summary className="text-xs cursor-pointer text-text-muted hover:text-text-primary transition-colors">
                      View implementation steps ({rec.steps.length})
                    </summary>
                    <ol className="mt-2 space-y-1.5">
                      {rec.steps.map((step, j) => (
                        <li key={j} className="flex items-start gap-2 text-xs">
                          <span className="w-4 h-4 rounded flex-shrink-0 flex items-center justify-center mt-0.5 text-xs font-bold"
                            style={{ background: 'rgba(0,212,255,0.1)', color: '#00d4ff' }}>{j + 1}</span>
                          <span style={{ color: '#94a3b8' }}>{step}</span>
                        </li>
                      ))}
                    </ol>
                  </details>

                  {/* References */}
                  <div className="flex flex-wrap gap-1.5 mt-3">
                    {rec.references.map(ref => (
                      <span key={ref} className="text-xs px-2 py-0.5 rounded font-mono"
                        style={{ background: '#0d1526', color: '#475569', border: '1px solid #1e3a5f' }}>{ref}</span>
                    ))}
                    {rec.mitigates.map(m => (
                      <span key={m} className="text-xs px-2 py-0.5 rounded font-mono"
                        style={{ background: 'rgba(168,85,247,0.08)', color: '#a855f7', border: '1px solid rgba(168,85,247,0.15)' }}>{m}</span>
                    ))}
                  </div>
                </div>
              </div>

              {/* Actions */}
              {!isApplied && (
                <div className="flex gap-2 mt-4 pt-4" style={{ borderTop: '1px solid #1e3a5f' }}>
                  <button onClick={() => markApplied(rec.id)}
                    className="btn-primary text-xs flex items-center gap-1.5">
                    <Check size={12} /> Mark as Applied
                  </button>
                  <button className="btn-ghost text-xs flex items-center gap-1.5">
                    <Clock size={12} /> Schedule
                  </button>
                  {rec.type === 'Automated' && (
                    <button className="text-xs px-3 py-1.5 rounded-lg flex items-center gap-1.5 transition-all"
                      style={{ background: 'rgba(0,212,255,0.1)', color: '#00d4ff', border: '1px solid rgba(0,212,255,0.2)' }}>
                      <Zap size={12} /> Auto-Execute
                    </button>
                  )}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}
